import Head from 'next/head'
import { Layout, RotaAutenticada, Dashboard } from 'components'
import { useDashboardService } from 'app/services/dashboard.service'
import { DashboardData } from 'app/models/dashboard'
import React from 'react'
import { useSession } from 'next-auth/client'


interface HomeProps {
  dashboard: DashboardData
}


const Home: React.FC<HomeProps> = (props: HomeProps) => {
  const {data: session} = useSession();
  console.log("session", session);
  
  return (
    <RotaAutenticada>
      <Head>
        <title>Grafica Metta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./logo.ico" />
      </Head>
      <Layout titulo="Dashboard">
        <Dashboard clientes={props.dashboard.clientes}
          produtos={props.dashboard.produtos}
          vendas={props.dashboard.vendas}
          vendasPorMes={props.dashboard.vendasPorMes}
        />
      </Layout>
    </RotaAutenticada>
  )
}

export async function getStaticProps(context:any) {

  const service = useDashboardService()
  const dashboard: DashboardData = await service.get();

  return {
    props: {
      dashboard
    },
    revalidate: 5// em segundos
  }
}

export default Home;